### ISSUE TITLE
Lowk doesnt work

### ISSUE THREAD

**Issue by LPlusBonk** [BeagleNF404/BeagleNF404s_packs#2]
![image](https://github.com/user-attachments/assets/423b7a27-b534-45f2-ae90-09a2604846a2)
![image](https://github.com/user-attachments/assets/04b8a8e5-4f66-4bb0-864a-f3b292f82853)

1.21.1
I have EMF and ETF

**Comment by BeagleNF404** [comment]
I'll look into the problem!
Sorry for the wait :)

**Comment by BeagleNF404** [comment]
Could you perhaps show me all the recourcepacks?

**Comment by LPlusBonk** [comment]
uhhhhhh,,,,,, 😰 sure... Good luck man, thanks for taking a look.

#### Texture Packs
- Fast Better Grass
- Shrimps-Distinct-Potions
- enchant icons 1.21 v1.3
- xali's Enchanted Books Addon...
- xali's Enchanted Books Fix v2...
- xali's enchanted books v0.13...
- VanillaTweaks Grass Sides
- Fancy Crops v1.0 f5-34
- xali's Enhanced Vanilla
- Seasonal Lush Caves (built-in: Fabric Seasons)
- Expressive Fresh Moves v3.0...
- Glass Pane Culling Fix (built-in: Continuity)
- Default Connected Textures (built-in: Continuity)
- Default Sound Pack (built-in: Presence Footsteps)

#### Mods
![image](https://github.com/user-attachments/assets/abe01a9e-a622-4da9-a656-39ce11b437d9)

**Comment by BeagleNF404** [comment]
The image of the mods you provided doesent seem to have 'Entity Model Features' (EMF). Is that due to the screenshot missing a few mods?

**Comment by LPlusBonk** [comment]
Sorry, somehow that screenshot isnt in alphabetical order. I do have EMF installed. Here is a screenshot in alphabetical order
![image](https://github.com/user-attachments/assets/969dfd67-eba0-4547-84bd-0aaeb59be576)
this definitely has every installed mod

**Comment by BeagleNF404** [comment]
I see you have another Vanilla Tweaks pack just below Fresh Animations, could that maybe help if you move it up 1? 
I have no clue, just guessing.
